# creation rules are evaluated sequentially, the first match will be evaluated
creation_rules:
  # dev encryption
  - path_regex: \.dev\.(yml|yaml)$
    encrypted_regex: "^(.*[Pp]ass.*|.*[Pp]wd.*|.*[Tt]oken.*)$"
    kms: "arn:aws:kms:us-east-1:654654270281:key/0be9b8e7-ada8-45b3-84d8-075d66359205"

  # prod encryption
  - path_regex: \.prod\.(yml|yaml)$
    encrypted_regex: "^(data|stringData)$"
    key_groups:
      - kms:
          - arn: "arn:aws:kms:us-west-2:361527076523:key/5052f06a-5d3f-489e-b86c-57201e06f31e+arn:aws:iam::361527076523:role/hiera-sops-prod,arn:aws:kms:eu-central-1:361527076523:key/cb1fab90-8d17-42a1-a9d8-334968904f94+arn:aws:iam::361527076523:role/hiera-sops-prod"
            role: "arn:aws:iam::927034868273:role/sops-dev-xyz"
            aws_profile: foo
